name: BetterMechanics
main: net.bettermechanics.BetterMechanics
version: 3.0.0-b000
authors: [ Edoxile, Sleaker ]
website: https://github.com/Sleaker/BetterMechanics
commands:
    pen:
        description: Change the text of signs
        usage: /pen [clear|set|setline|help]
        aliases: p
    bettermechanics:
        description: Change the text of signs
        usage: /bettermechanics reload <cauldron>
        aliases: bm